/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PortfolioHolding = IDL.Record({
  'avgCost' : IDL.Float64,
  'quantity' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PortfolioSummary = IDL.Record({
  'totalValue' : IDL.Float64,
  'holdings' : IDL.Vec(PortfolioHolding),
  'totalGainLoss' : IDL.Float64,
});
export const Stock = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'name' : IDL.Text,
  'open' : IDL.Float64,
  'priceHistory' : IDL.Vec(IDL.Float64),
  'volume' : IDL.Nat,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'getPortfolio' : IDL.Func([], [PortfolioSummary], ['query']),
  'getStock' : IDL.Func([IDL.Text], [IDL.Opt(Stock)], ['query']),
  'getStocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PortfolioHolding = IDL.Record({
    'avgCost' : IDL.Float64,
    'quantity' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PortfolioSummary = IDL.Record({
    'totalValue' : IDL.Float64,
    'holdings' : IDL.Vec(PortfolioHolding),
    'totalGainLoss' : IDL.Float64,
  });
  const Stock = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'name' : IDL.Text,
    'open' : IDL.Float64,
    'priceHistory' : IDL.Vec(IDL.Float64),
    'volume' : IDL.Nat,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'getPortfolio' : IDL.Func([], [PortfolioSummary], ['query']),
    'getStock' : IDL.Func([IDL.Text], [IDL.Opt(Stock)], ['query']),
    'getStocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };